# Site settings
title: graphic-zhang - algorithm engineer of computer vision 
description: "A blog about graphic-zhang ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://graphic-zhang.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: graphic-zhang
user_title: graphic-zhang - FrontEnd
email: zhangxiang941211@gmail.com
github_username:  graphic-zhang  
linkedin_public_url: 翔-张-783142117 # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
profile_picture: https://octodex.github.com/images/megacat.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my resume
      url: /resume
      key_trigger: 2
    #- title: series
    #  url: /series
    #  key_trigger: 3
    #- title: tags
    #  url: /tags
    #  key_trigger: 4
    #- title: about me
    #  url: /about
    #  key_trigger: 2
  section_2:
    - title: github
      url: https://www.github.com/graphic-zhang
      new_tab: true
      key_trigger: g
    #- title: twitter
    #  url: http://www.twitter.com/victorvoid
    #  key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
